export const FETCH_PRODUCTDETAIL_REQUEST = 'FETCH_PRODUCTDETAIL_REQUEST'
export const FETCH_PRODUCTDETAIL_SUCCESS = 'FETCH_PRODUCTDETAIL_SUCCESS'
export const FETCH_PRODUCTDETAIL_FAILURE = 'FETCH_PRODUCTDETAIL_FAILURE'
export const FETCH_PRODUCTDETAIL_URL = 'http://localhost:3000/products'