export const ADD_PRODUCT_CART = 'FETCH_CART_SUCCESS'
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART'
export const CHANGE_PRODUCT_QUANTITY_IN_CART = 'CHANGE_PRODUCT_QUANTITY_IN_CART'
export const CLEAR_CART = 'CLEAR_CART'