export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
export const DEFAULT_SORT = 'Default'
export const HIGH_TO_LOW_SORT = 'High To Low'
export const LOW_TO_HIGH_SORT = 'Low To High'
export const URL_PRODUCTS_FETCH = 'http://localhost:3001/products'
export const PAGE_QUERY = '_page='
export const DEFAULT_LIMIT_QUERY = '_limit=8'
export const TITLE_LIKE_QUERY = 'title_like='
export const SORT_PRICE_QUERY = '_sort=price'
export const ORDER_QUERY = '_order='
export const ASC_QUERY = 'asc'
export const DESC_QUERY = 'desc'
export const HEADER_TOTAL_COUNT = 'x-total-count'